repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: flake8
        language: python_venv
-   repo: https://github.com/timothycrosley/isort
    rev: 4.3.20
    hooks:
    -   id: isort
        language: python_venv
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.701
    hooks:
    -   id: mypy
        language: python_venv
