dist: xenial
language: python
stages:
- lint
- test
- docs
- deploy
cache:
  pip: true
jobs:
  include:
  - stage: lint
    python: '3.8'
    script:
    - make lint
  - stage: test
    python:
    - '3.8'
    - nightly
    matrix:
      allow_failures:
      - python: nightly
    script:
    - make release
    env:
    - CODECOV_TOKEN="db11eab9-1a10-45bf-aed0-9d51394dc6dd"
    after_success:
    - codecov
  - stage: docs
    python: '3.8'
    allow_failures: true
    script:
    - make docs
  - stage: deploy
    python: '3.8'
    script:
    - make release
    deploy:
      provider: pypi
      user: __token__
      on:
        tags: True
      password:
        secure: CwVl2ZAATemo9V4UDubmGVFv79MtFWa64+odGcsaOSl1DghTD13CMg3VrXkCfP51N8YxIlyY2DzyAl8GqUvc0hOZeY7TN+pQHUKGiuSjqob3tZ0Lx0k6zPS7nNTvowv0zMo0+ZB2L4jBpz6QeGYwGk7v6J3kXqNv6E5BDCJa4Y7zZE0LCHDYyv41beqpfYEtEoItYCwTjV+P3WWR5yGy6bIUpSoVSWGsCRUiawLT7SruQqKp+GuXuDJn7AkUnCP/kgWq3A/XUOsNwuarLtiNvh6q8Isqj2BG5iXG04csAtxaR37F7yipRHTtbOoMjQfcLU9ohn+2TNW9D99evJD2/HAiymXqZb/FKtDbEZsY3sfqRQAndcQQwZdxwyI9c+pj9HlVAd3BM0mZSYzxgj4UWPG8lGx9BybUuO8kwO99/OphndZYxS3bcdNotlTYdgdkUtZgMJ9h97h3z1XRRUYymdLrZVJzD/H3QqYJYVpOEieHRLSunKjaSOHAHXk/ICJ9zkLRMiHDR5hl3msAWGxRoQNaW5O6kvRaSoUy5hkXKLU5g+F15Cu2/1oo1RQm0mHPSISh2Nn6dFt/LhG/CvaPU10esV9N9SW9cIMv5+nYQP7fYGwirRaiiW3cuYvnVJJKGTMIQxiOEGMG2/3jwXd2ePz7lxYbvfmPgIFQEHd/Yi4=
